/*
Before starting!

Run this command as super(admin|user|root) in your Postgres database, directly on the database you are going to use
for this application

-- below here, run as admin
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA pg_catalog;

CREATE OR REPLACE FUNCTION filter(needles text, VARIADIC haystacks text [])
RETURNS boolean AS $$
SELECT needles IS NULL OR trim(needles) = '' OR EXISTS(
    SELECT DISTINCT 1
    FROM unnest(haystacks) haystack,
    unnest(string_to_array(needles, ',')) needle
    WHERE unaccent(haystack) ILIKE '%' || unaccent(needle) || '%');
$$ LANGUAGE SQL;
*/

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1 (Debian 12.1-1.pgdg100+1)
-- Dumped by pg_dump version 12.0

-- Started on 2020-05-20 03:58:08 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 185025)
-- Name: administration; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA administration;


SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 185028)
-- Name: authorities; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.authorities (
    id bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    name character varying(45) NOT NULL
);


--
-- TOC entry 205 (class 1259 OID 185033)
-- Name: authorities_audit; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.authorities_audit (
    id bigint NOT NULL,
    revision bigint NOT NULL,
    revision_type smallint,
    name character varying(45)
);


--
-- TOC entry 203 (class 1259 OID 185026)
-- Name: authorities_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.authorities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.authorities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 185040)
-- Name: grants; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.grants (
    id bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    id_authority bigint NOT NULL,
    id_user bigint NOT NULL
);


--
-- TOC entry 208 (class 1259 OID 185045)
-- Name: grants_audit; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.grants_audit (
    id bigint NOT NULL,
    revision bigint NOT NULL,
    revision_type smallint,
    id_authority bigint,
    id_user bigint
);


--
-- TOC entry 206 (class 1259 OID 185038)
-- Name: grants_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.grants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.grants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 185052)
-- Name: user_activations; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.user_activations (
    id bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    activated_on timestamp without time zone,
    activation_status character varying(20) NOT NULL,
    expire_in timestamp without time zone NOT NULL,
    token character varying(20) NOT NULL,
    id_user bigint NOT NULL
);


--
-- TOC entry 211 (class 1259 OID 185057)
-- Name: user_activations_audit; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.user_activations_audit (
    id bigint NOT NULL,
    revision bigint NOT NULL,
    revision_type smallint,
    activated_on timestamp without time zone,
    activation_status character varying(20),
    expire_in timestamp without time zone,
    token character varying(20),
    id_user bigint
);


--
-- TOC entry 209 (class 1259 OID 185050)
-- Name: user_activations_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.user_activations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.user_activations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 185064)
-- Name: users; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.users (
    id bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone,
    active boolean NOT NULL,
    email character varying(90) NOT NULL,
    name character varying(90) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(45) NOT NULL
);


--
-- TOC entry 214 (class 1259 OID 185069)
-- Name: users_audit; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.users_audit (
    id bigint NOT NULL,
    revision bigint NOT NULL,
    revision_type smallint,
    active boolean,
    email character varying(90),
    name character varying(90),
    password character varying(255),
    username character varying(45)
);


--
-- TOC entry 212 (class 1259 OID 185062)
-- Name: users_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 185078)
-- Name: revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revisions (
    id bigint NOT NULL,
    created_by character varying(45) NOT NULL,
    created_on timestamp without time zone NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 185076)
-- Name: revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2972 (class 0 OID 185028)
-- Dependencies: 204
-- Data for Name: authorities; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.authorities (id, created_on, updated_on, name) VALUES (1, '2020-05-20 00:56:50.541627', NULL, 'ADMINISTRATOR');
INSERT INTO administration.authorities (id, created_on, updated_on, name) VALUES (2, '2020-05-20 00:56:50.565625', NULL, 'LIBRARIAN');


--
-- TOC entry 2973 (class 0 OID 185033)
-- Dependencies: 205
-- Data for Name: authorities_audit; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.authorities_audit (id, revision, revision_type, name) VALUES (1, 2, 0, 'ADMINISTRATOR');
INSERT INTO administration.authorities_audit (id, revision, revision_type, name) VALUES (2, 3, 0, 'LIBRARIAN');


--
-- TOC entry 2975 (class 0 OID 185040)
-- Dependencies: 207
-- Data for Name: grants; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.grants (id, created_on, updated_on, id_authority, id_user) VALUES (1, '2020-05-20 00:56:50.594638', NULL, 1, 2);


--
-- TOC entry 2976 (class 0 OID 185045)
-- Dependencies: 208
-- Data for Name: grants_audit; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.grants_audit (id, revision, revision_type, id_authority, id_user) VALUES (1, 4, 0, 1, 2);


--
-- TOC entry 2978 (class 0 OID 185052)
-- Dependencies: 210
-- Data for Name: user_activations; Type: TABLE DATA; Schema: administration; Owner: -
--



--
-- TOC entry 2979 (class 0 OID 185057)
-- Dependencies: 211
-- Data for Name: user_activations_audit; Type: TABLE DATA; Schema: administration; Owner: -
--



--
-- TOC entry 2981 (class 0 OID 185064)
-- Dependencies: 213
-- Data for Name: users; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.users (id, created_on, updated_on, active, email, name, password, username) VALUES (2, '2020-05-20 00:56:50.225626', NULL, true, 'admin@admin.eti.br', 'Administrador', '$2a$10$ZRQdavHD/rUzhv2/iN6woelvG3Px8ubs3t0HgeLEkY896a1E.QL2q', 'admin');


--
-- TOC entry 2982 (class 0 OID 185069)
-- Dependencies: 214
-- Data for Name: users_audit; Type: TABLE DATA; Schema: administration; Owner: -
--

INSERT INTO administration.users_audit (id, revision, revision_type, active, email, name, password, username) VALUES (2, 1, 0, true, 'admin@admin.eti.br', 'Administrador', '$2a$10$ZRQdavHD/rUzhv2/iN6woelvG3Px8ubs3t0HgeLEkY896a1E.QL2q', 'admin');
INSERT INTO administration.users_audit (id, revision, revision_type, active, email, name, password, username) VALUES (2, 4, 1, true, 'admin@admin.eti.br', 'Administrador', '$2a$10$ZRQdavHD/rUzhv2/iN6woelvG3Px8ubs3t0HgeLEkY896a1E.QL2q', 'admin');


--
-- TOC entry 2984 (class 0 OID 185078)
-- Dependencies: 216
-- Data for Name: revisions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.revisions (id, created_by, created_on) VALUES (1, 'anonymous', '2020-05-20 00:56:50.262');
INSERT INTO public.revisions (id, created_by, created_on) VALUES (2, 'anonymous', '2020-05-20 00:56:50.556');
INSERT INTO public.revisions (id, created_by, created_on) VALUES (3, 'anonymous', '2020-05-20 00:56:50.567');
INSERT INTO public.revisions (id, created_by, created_on) VALUES (4, 'anonymous', '2020-05-20 00:56:50.631');


--
-- TOC entry 2990 (class 0 OID 0)
-- Dependencies: 203
-- Name: authorities_id_seq; Type: SEQUENCE SET; Schema: administration; Owner: -
--

SELECT pg_catalog.setval('administration.authorities_id_seq', 2, true);


--
-- TOC entry 2991 (class 0 OID 0)
-- Dependencies: 206
-- Name: grants_id_seq; Type: SEQUENCE SET; Schema: administration; Owner: -
--

SELECT pg_catalog.setval('administration.grants_id_seq', 1, true);


--
-- TOC entry 2992 (class 0 OID 0)
-- Dependencies: 209
-- Name: user_activations_id_seq; Type: SEQUENCE SET; Schema: administration; Owner: -
--

SELECT pg_catalog.setval('administration.user_activations_id_seq', 1, false);


--
-- TOC entry 2993 (class 0 OID 0)
-- Dependencies: 212
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: administration; Owner: -
--

SELECT pg_catalog.setval('administration.users_id_seq', 2, true);


--
-- TOC entry 2994 (class 0 OID 0)
-- Dependencies: 215
-- Name: revisions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.revisions_id_seq', 4, true);


--
-- TOC entry 2821 (class 2606 OID 185037)
-- Name: authorities_audit authorities_audit_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.authorities_audit
    ADD CONSTRAINT authorities_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2819 (class 2606 OID 185032)
-- Name: authorities authorities_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.authorities
    ADD CONSTRAINT authorities_pkey PRIMARY KEY (id);


--
-- TOC entry 2825 (class 2606 OID 185049)
-- Name: grants_audit grants_audit_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.grants_audit
    ADD CONSTRAINT grants_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2823 (class 2606 OID 185044)
-- Name: grants grants_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.grants
    ADD CONSTRAINT grants_pkey PRIMARY KEY (id);


--
-- TOC entry 2827 (class 2606 OID 185075)
-- Name: user_activations uk_j6v6u6x10v35xt5yo60a83210; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.user_activations
    ADD CONSTRAINT uk_j6v6u6x10v35xt5yo60a83210 UNIQUE (token);


--
-- TOC entry 2831 (class 2606 OID 185061)
-- Name: user_activations_audit user_activations_audit_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.user_activations_audit
    ADD CONSTRAINT user_activations_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2829 (class 2606 OID 185056)
-- Name: user_activations user_activations_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.user_activations
    ADD CONSTRAINT user_activations_pkey PRIMARY KEY (id);


--
-- TOC entry 2835 (class 2606 OID 185073)
-- Name: users_audit users_audit_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users_audit
    ADD CONSTRAINT users_audit_pkey PRIMARY KEY (id, revision);


--
-- TOC entry 2833 (class 2606 OID 185068)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2837 (class 2606 OID 185082)
-- Name: revisions revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisions
    ADD CONSTRAINT revisions_pkey PRIMARY KEY (id);


--
-- TOC entry 2838 (class 2606 OID 185083)
-- Name: authorities_audit fk_authorities_audit_revisions; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.authorities_audit
    ADD CONSTRAINT fk_authorities_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2841 (class 2606 OID 185098)
-- Name: grants_audit fk_grants_audit_revisions; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.grants_audit
    ADD CONSTRAINT fk_grants_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2839 (class 2606 OID 185088)
-- Name: grants fk_grants_authorities; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.grants
    ADD CONSTRAINT fk_grants_authorities FOREIGN KEY (id_authority) REFERENCES administration.authorities(id);


--
-- TOC entry 2840 (class 2606 OID 185093)
-- Name: grants fk_grants_users; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.grants
    ADD CONSTRAINT fk_grants_users FOREIGN KEY (id_user) REFERENCES administration.users(id);


--
-- TOC entry 2843 (class 2606 OID 185108)
-- Name: user_activations_audit fk_user_activations_audit_revisions; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.user_activations_audit
    ADD CONSTRAINT fk_user_activations_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


--
-- TOC entry 2842 (class 2606 OID 185103)
-- Name: user_activations fk_user_activations_users; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.user_activations
    ADD CONSTRAINT fk_user_activations_users FOREIGN KEY (id_user) REFERENCES administration.users(id);


--
-- TOC entry 2844 (class 2606 OID 185113)
-- Name: users_audit fk_users_audit_revisions; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users_audit
    ADD CONSTRAINT fk_users_audit_revisions FOREIGN KEY (revision) REFERENCES public.revisions(id);


-- Completed on 2020-05-20 03:58:08 UTC

--
-- PostgreSQL database dump complete
--